### ISSUE TITLE
Integrity of Vault bucket entries is not verified 

### ISSUE THREAD

**Issue by alaisi** [NitorCreations/vault#23]
Vault encrypts files with AES in CTR mode which does *not* verify the integrity of the ciphertext. This allows an attacker who has compromised the S3 bucket to tamper with the encrypted content without detection, possibly leading to leaking the plaintext data.

# Example

Alice has created a vaulted entry:

```bash
alice@cd:~$ vault \
    -s github_client_endpoint \
    -v 'https://api.github.com/?client_id=alice&client_secret=topsecret'
```

Mallory has gained write access to the S3 bucket (by exploiting a botched ACL, leaked IAM credentials etc.). As Mallory has no access to KMS, he cannot decrypt the vaulted secret. However, Mallory can try to guess parts of the plaintext and xor the ciphertext with the guess and target value to produce a new valid ciphertext.

In this case, if Mallory manages to guess the beginning of the plaintext, he can swap the URL to point to a malicious server:

```java
byte[] cipherText = getFromBucket();

byte[] guess  = "https://api.github.com".getBytes("utf-8");
byte[] target = "https://example.com/xx".getBytes("utf-8");
byte[] tamperedCipherText = Arrays.copyOf(cipherText, cipherText.length);
for(int i = 0; i < guess.length; i++) {
    tamperedCipherText[i] = (byte) (tamperedCipherText[i] ^ guess[i]);
    tamperedCipherText[i] = (byte) (tamperedCipherText[i] ^ target[i]);
}

putToBucket(tamperedCipherText);
```

When Alices application uses Vault to read to data, the tampering goes unnoticed, the ciphertext is decrypted to the chosen plaintext prefix and the remaining original plaintext is leaked to Mallory (e.g. in an HTTP request performed by a Lambda).

```bash
alice@cd:~$ vault -l github_client_endpoint
https://example.com/xx?client_id=alice&client_secret=topsecret
```

## Fixing this

* Use GCM instead of CTR
* Use a random IV for each encryption operation
    * Store the IV with the ciphertext (prepending IV to the ciphertext is a popular choice)

**Comment by alaisi** [comment]
All formats that have a fixed structure help quite a lot in the guessing part. For example private keys in PEM, DER and SSH key formats are encoded ASN.1 sequences with a fairly static header. So it would be possible to change key type or key parts (e.g. RSA private exponent) if one would have an oracle at hand, for example a Lambda that would return a different HTTP error based on if the ciphertext decrypted to a valid DER key or not.

**Comment by psiniemi** [comment]
The idea for adding random IV has so far been to add another object into the bucket. That object could also have hashes of the cleartext and ciphertext. Objects created with the old versions could have these added in case the accessor has write access to the bucket. Breaking backwards compatibility would be a major hassle. We could also add a command to re-encrypt and randomize IV for all objects in a bucket. The amount of secrets out there is not too big for this to be feasible.

**Comment by alaisi** [comment]
Storing a (mac) hash of the ciphertext would be unnecessary with authenticated encryption such as GCM. And storing a hash of plaintext would leak quite a lot of information of the vaulted secret.

I would suggest storing a ”meta” object in the bucket with the format:

’’’javascript
}
    ”alg”: ”A256GCM”,
    ”timestamp”: <unix time>
}
’’’

Encryption would be performed with AES/GCM/NoPadding with a random 16-byte IV and the meta object bytes as AAD.

The encrypted object stored in the bucket would contain the 16-byte IV concatenated with the ciphertext.

With this setup the change can be backward compatible (if no meta is found, use the CTR decryption). The ciphertext, meta and IV are all covered by the GCM internal hash and tampering with any of the values would prevent decryption.

**Comment by psiniemi** [comment]
Python 0.21 now has this. As long as there are older versions out there, we need to encrypt both versions. Newer versions will use the authenticated version unless there is no *.meta object for the ciphertext. Unfortunately this means that the attack still works - you just need to delete the meta object first. The attack assumes write access to the bucket and adding delete access is not such a leap.

We can delete the old encryption as soon as we are confident that no significant installations of the older versions exist. This will be quite a chore though since it is installed on every instance that has ndt set up to use vault for secrets, There are dozens if not hundreds of those and they might not get upgraded for months. Additionally there are some lambdas out there that use this or the javasrcript version.

For now we can just advice to be vigilant about write/delete access to the vault bucket. In general they are pretty well protected since they contain secrets.

Also this needs to be implemented for javascript and java variants.
